### ISSUE TITLE
Contact email

### ISSUE THREAD

**Issue by God-damnit-all** [aidsrentfree/aidsrentfree.github.io#2]
There are some things I would like to be able to submit anonymously without having to rely on posting in the latest 4chan thread and hoping it gets noticed.

I tried the redirection email associated with your account ( ![image](https://user-images.githubusercontent.com/53661808/155199978-acd12f8e-4611-4678-b116-d7c6a16b8e3b.png) ), but I didn't get a response.

**Comment by aidsrentfree** [comment]
Sorry about that. It's a buggy thing I frankly need to change. What would you like to submit? If you want I can give you my other email to use instead?

**Comment by God-damnit-all** [comment]
> What would you like to submit?

It wouldn't be very anonymous if I said so here.

> If you want I can give you my other email to use instead?

Sure. I recommend doing what I did above, taking a screenshot of it in a form that a bot can't just scrape or OCR capture.

**Comment by aidsrentfree** [comment]
Fair point.
At this point, I've quickly set up a ready-made one. (![image](https://user-images.githubusercontent.com/86891978/155201914-4a0fdee8-27e7-494b-a033-9b04e31501dd.png))

**Comment by aidsrentfree** [comment]
Hey, if you've sent an email, I haven't received it.

**Comment by God-damnit-all** [comment]
> Hey, if you've sent an email, I haven't received it.

Sorry about that. Winter storm took out the Internet. It's sent.
